fix flawed implementation
fix:
* tmux options
* history buffer
* bash history
* save acts on foreground process, instead of starting process
* convert indenting tabs to spaces

diff --git a/tsgc-save b/tsgc-save
--- a/tsgc-save
+++ b/tsgc-save
@@ -16,32 +16,63 @@ removeDir() {
 }
 
 saveTmuxConf() {
-  echo "### Global Options" > "$2"
-  tmux show-options -g >> "$2"
+#  echo "### Global Options" > "$2"
+#  tmux show-options -g >> "$2"
 
   echo -e "\n### Server Options" >> "$2"
-  tmux show-options -s >> "$2"
+  while IFS=$'\n' read -r tmux_option; do
+    echo "set-option -s ${tmux_option}" >> "$2"
+  done < <(tmux show-options -s)
 
   echo -e "\n### Session Options" >> "$2"
-  tmux show-options -t "$1" >> "$2"
+  while IFS=$'\n' read -r tmux_option; do
+    echo "set-option -s ${tmux_option}" >> "$2"
+  done < <(tmux show-options -t "$1")
 }
 
 saveBashHistory() {
-  gdb -batch -x <<-EOF
-	attach $1
-	call write_history("${session_saveDir}/${pane_target}/${1}.bashHistory")
-	
-	EOF
-
-  echo "tmux send-keys -t \"${pane_target}\" \"history -r '${session_saveDir}/${pane_target}/${1}.bashHistory'\" \"Enter\"" >> "${session_restoreFile}"
+  tmux send-keys -t "${pane_target}" "C-e" "C-u" "history -w '${pane_saveDir}/${1}.bashHistory'" "Enter" "C-y"
+  echo "tmux send-keys -t \"${pane_target}\" \"history -r '${pane_saveDir}/${1}.bashHistory'\" \"Enter\"" >> "${session_restoreFile}"
 }
 
 saveVimSession() {
-  vimSessionFile=$(printf ':mksession! %q/%q/%q.vimSession\n' "${session_saveDir}" "${pane_target}" "${1}")
+  local vimSessionFile=$(printf ':mksession! %q/%q.vimSession\n' "${pane_saveDir}" "${1}")
   tmux send-keys -t "${pane_target}" "Escape" "${vimSessionFile}" "Enter"
-  printf "tmux send-keys -t \"${pane_target}\" 'vim -S \"%q/%q/%q.vimSession\"' \"Enter\"\n" "${session_saveDir}" "${pane_target}" "${1}" >> "${session_restoreFile}"
+  printf "tmux send-keys -t \"${pane_target}\" 'vim -S \"%q/%q.vimSession\"' \"Enter\"\n" "${pane_saveDir}" "${1}" >> "${session_restoreFile}"
 }
 
+getForegroundProcess() {
+  while IFS=$'\n' read -r process; do
+    IFS=' ' read foregroundProcess_pid foregroundProcess_comm foregroundProcess_tpgid <<<"$process"
+    if [[ "$foregroundProcess_tpgid" -eq "$foregroundProcess_pid" ]]; then
+      return 0
+    fi
+  done < <(ps -o pid=,comm=,tpgid= --tty "$pane_tty")
+
+  return 1
+}
+
+saveProcess() {
+  local process_comm="$2"
+  local process_pid="$1"
+
+  if [[ "$process_comm" == "vim" ]]; then
+    # vim plugin: save session
+    saveVimSession "$process_pid"
+  elif [[ "$process_comm" == "bash" ]]; then
+    # bash plugin: save bash history
+    saveBashHistory "$process_pid"
+  else
+    removeDir "$session_saveDir"
+    echo "tmux sgc: process (pid: ${process_pid}) in pane not "\
+      "recognized. The term process refers to the process's program."\
+      "A process must have a save and restore action associated with "\
+      "it. tmux sgc does not magically know how to handle unknown"\
+      " processes. Create a plugin for the process or an"\
+      " issue." >&2
+    exit 1
+  fi
+}
 
 # Global
 globalEnvironment=$(tmux show-environment -g)
@@ -71,6 +102,11 @@ fi
 # Sessions
 if [[ ! -d "${sessionsDir}" ]]; then
   mkdir "${sessionsDir}"
+
+  if [[ $? -ne 0 ]]; then
+    echo "tmux sgc: failed to make session storage directory" >&2
+    exit 1
+  fi
 fi
 
 server_sessionList=$(tmux list-sessions -F "#{session_name}"$'\036'"#{session_attached}")
@@ -86,48 +122,51 @@ if [[ -n "$server_sessionList" ]]; then
     session_tmuxConf="${session_saveDir}/.tmux.conf"
     window_num=0
 
-    if [[ ! -d "$session_saveDir" ]]; then
-      mkdir "$session_saveDir"
-    fi
+    mkdir -p "$session_saveDir"
 
     saveTmuxConf "$session_name" "$session_tmuxConf"
 
     echo "#!/usr/bin/env bash" > "${session_restoreFile}"
     echo "# # session: ${session_name}" >> "${session_restoreFile}"
     cat >> "$session_restoreFile" <<-EOL
-			tmux has-session -t "${session_name}" &>/dev/null
-			if [[ ! \$? ]]; then
-			  echo "The session \"${session_name}\" already exists. This script does not overwrite sessions." >&2
-			  exit 1
-			fi
-		EOL
+      tmux has-session -t "${session_name}" &>/dev/null
+      if [[ ! \$? ]]; then
+        echo "The session \"${session_name}\" already exists. This script does not overwrite sessions." >&2
+        exit 1
+      fi
+    EOL
 
     while IFS=$'\n' read -r window; do
       IFS=$'\036' read window_name window_index window_layout window_active window_flags <<<"$window"
       window_target="${session_name}:${window_index}"
       window_paneList=$(tmux list-panes -t "${window_target}" -F "#{pane_id}"$'\036'"#{pane_start_path}"$'\036'"#{pane_start_command}"$'\036'"#{pane_active}"$'\036'"#{pane_pid}")
+      window_saveDir="${session_saveDir}/${window_num}"
+      window_tmuxConf="${window_saveDir}/.tmux.conf"
       pane_num=0
 
-      # TODO: a per window tmux save and restore.
-      # currently, the window tmux configs are saved to the session tmux conf
-      # which will cause the last saved window's tmux conf to win and be set
-      # for all windows.
-      echo -e "\n### Window Options" >> "$session_tmuxConf"
-      tmux show-options -w -t "${window_target}" >> "$session_tmuxConf"
+      mkdir -p "$window_saveDir"
 
       echo -e "\n# ## window: ${window_name}" >> "${session_restoreFile}"
 
+      # save tmux window options
+      echo -e "\n## Window $window_num Options" > "$window_tmuxConf"
+      #tmux show-options -w -t "${window_target}" >> "$window_tmuxConf"
+      while IFS=$'\n' read -r tmux_option; do
+        echo "tmux set-option -w -t ${window_target} ${tmux_option}" >> "$window_tmuxConf"
+      done < <(tmux show-options -w -t "${window_target}")
+
       while IFS=$'\n' read -r pane; do
         IFS=$'\036' read pane_id pane_start_path pane_start_command pane_active pane_pid <<<"$pane"
-        pane_comm=($(</proc/${pane_pid}/comm))
+        IFS=' ' read pane_comm pane_tpgid pane_tty < <(ps -o comm=,tpgid=,tty= --pid "$pane_pid")
         pane_target="${window_target}.${pane_num}"
-        pane_historyBufferFile="${session_saveDir}/${pane_target}/historyBuffer"
+        pane_saveDir="${window_saveDir}/${pane_num}"
+        pane_historyBufferFile="${pane_saveDir}/historyBuffer"
 
-        mkdir -p "${session_saveDir}/${pane_target}"
+        mkdir -p "${pane_saveDir}"
 
         echo -e "\n# ### pane: ${pane_num}" >> "${session_restoreFile}"
 
-        # save and load panes
+        # save panes
         #
         # starting a new session or window inherantly includes a new pane. So,
         # their commands are built when looping through panes, panes are available.
@@ -159,43 +198,49 @@ if [[ -n "$server_sessionList" ]]; then
           echo "}" >> "${session_restoreFile}"
         fi
 
+        if [[ "$pane_num" == 0 ]]; then
+          # add restore tmux window options
+          echo ". \"${window_tmuxConf}\"" >> "${session_restoreFile}"
+        fi
+
         # save environment per pane, PID
         # /proc/<PID>/environ
 
-        # save and load history buffer
-        # this method relies on bash to restore the history. So, if bash
-        # isn't the $pane_pid, restoration fails.
+        # save history buffer
         tmux capture-pane -S -999999 -t "${pane_id}"
         tmux save-buffer -b 0 "$pane_historyBufferFile"
         tmux delete-buffer -b 0
-
-        echo "tmux send-keys -t \"${pane_target}\" 'cat \"${pane_historyBufferFile}\" > \$(tty)' \"Enter\"" >> "${session_restoreFile}"
+        echo "cat \"${pane_historyBufferFile}\" >> /dev/${pane_tty}" >> "${session_restoreFile}"
  
         # action based on pid
-        # TODO: change into a plugin interface:
+        # TODO change into a plugin interface:
         # the process tree will be available to plugins, so the plugins may
         # take action based on order and parent processes to ensure the correct
         # saving and restoration steps are taken
-        pane_processes=$(ps -o pid=,comm= --ppid "${pane_pid}")
-        pane_processes="${pane_pid} ${pane_comm}$'\n'${pane_pid_children}"
-        while IFS=$'\n' read -r process; do
-          IFS=' ' read process_pid process_comm <<<"$process"
+        #
+        # 1. Find the foreground process.
+        # 2. take action on it (e.g. save it's "session")
+        # TODO:
+        # 3. pause it (send to background or kill)
+        # 4. repeat steps 1-3 until foreground process id is the pane_pid
+        # 5. restore paused processes (foreground or rebuild)
 
-          if [[ "$process_comm" == "vim" ]]; then
-            # vim plugin: save session
-            saveVimSession "$process_pid"
-          elif [[ "$process_comm" == "bash" ]]; then
-            # bash plugin: save bash history
-            saveBashHistory "$process_pid"
+        if [[ "$pane_tpgid" -eq "$pane_pid" ]]; then
+            saveProcess "$pane_pid" "$pane_comm"
+        else
+          foregroundProcess_pid='';
+          foregroundProcess_comm='';
+          foregroundProcess_tpgid='';
+          getForegroundProcess
+
+          if [[ $? -eq 0 ]]; then
+            saveProcess "$foregroundProcess_pid" "$foregroundProcess_comm"
           else
-            removeDir "$session_saveDir"
-            echo "tmux sgc: process in pane not recognized. "\
-              "A process must have a save and restore action associated with "\
-              "it. tmux sgc does not magically know how to handle unknown"\
-              " processes, programs." >&2
+            echo "tmux sgc: Failed to find foreground process in tmux target \"$pane_target\"." >&2
+            exit 1
           fi
-        done <<<"$pane_processes"
-        
+        fi
+
         # afs retoken
         #http://www.sph.umich.edu/computing/unix/screen.html
         #kinit ; aklog
@@ -218,7 +263,7 @@ if [[ -n "$server_sessionList" ]]; then
       (( window_num += 1 ))
     done <<<"$session_windowList"
 
-    # save and load paste buffers
+    # save paste buffers
     #
     # a copy of the global buffers is saved for each session. And, buffers are
     # appended to the buffer list when loaded.
